apiVersion: batch/v1
kind: Job
metadata:
  name: test-sampleapp
  namespace: test
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 1
  template:
    spec:
      serviceAccountName: test
      volumes:
        - name: script
          configMap:
            name: script-sampleapp
      restartPolicy: Never
      containers:
        - name: kanata-test
          image: gcr.io/cloud-builders/kubectl
          #image: debian:stable-slim
          imagePullPolicy: Always
          command: ["bash", "/mnt/test.sh"]
          volumeMounts:
            - mountPath: /mnt/test.sh
              name: script
              subPath: "test.sh"
          env:
            - name: "Namespace"
              value: "test"
            - name: "Ingress"
              value: "kanata-ingress"
            - name: "ProdFQDN"
              value: "kanata.local"
            - name: "Expect_Response"
              value: "${parameters.POD_VERSION}"
